### PR TITLE
Added New Features

### PR DESCRIPTION
**Pull request by hereisnaman**
@prateek27 @omerjerk @championswimmer Have added some new features:

**Update** Also solved: https://github.com/coding-blocks/ide/issues/65 Input box integrated with LocalStorage, Auto Save every 30 seconds added.
image

# File Name Input Box
Have added input for file name above the editor. The File Name textbox is integrated with localStorage, Upload and Download functions. That means:

- It will be updated when a file is uploaded
- It will be restored from the localStorage
- It will be the name of the downloaded file
image

# Added Settings Modal
Replaces the Theme dropdown from the panel heading with the Setting Button which onClick will display a modal with many setting options. All the options are integrated will localStorage. The setting will get restored from localStorage.
image

## Themes
Have added more themes. Now the total number of themes are **14**. Separate section for dark and light themes.
image

## Fonts
Added options to select different fonts (only for editor). Total number of fonts are: **15**. 
image

## Font Size
Added option to change editor font size. 
image

## Reset button
Resets all the settings to default.

### CODE REVIEW

**Comment by sirjan13** [comment]
@hereisnaman This is really cool!

**Comment by hereisnaman** [comment]
@sirjan13 thanks bro :).

**Comment by prateek27** [comment]
These features are really cool. Giving a BOUNTY of 500 for making these :) @hereisnaman

**Comment by hereisnaman** [comment]
@prateek27 thanks a lot :) .

**Pull request merged**
