### PR TITLE
Custom Input toggle resolve

### PR DESCRIPTION
**Pull request by Vatsalgarg1617**
@championswimmer  done #52.. Pls review my code

### CODE REVIEW

**Comment by championswimmer** [comment]
Screenshsots please for any UI changes

**Comment by Vatsalgarg1617** [comment]
image
image

**Comment by Vatsalgarg1617** [comment]
@championswimmer  pls review my code

**Comment by omerjerk** [comment]
You don't seem to be handling the case of setting custom input to null when the custom input box is closed.

**Comment by Vatsalgarg1617** [comment]
@omerjerk custom input to null when the custom input box is closed

**Comment by omerjerk** [comment]
It has been fixed already. Thanks a lot for your efforts. :)

**Pull request closed without merging**
