### PR TITLE
Added menus to title-bar

### LINKED ISSUE #277: Add menus to title bar
There are so many buttons in the title bar, which do not fit on small screens and also creates a lot of noise. 

Lets categorize the options and create different menus for them.
```
1 Run Button
2 Language Selector
3 Input
4 File
   4.1 New
   4.2 Save
   4.3 Upload
   4.4 Download
5 Settings
6 Share
7 Shortcuts
8 Username
  8.1 saved codes
  8.2 logout
```

### PR DESCRIPTION
**Pull request by dakshkhetan**
Fixed #277 
- added dropdowns (for File, View & User) to title-bar as required.
- dropdowns appear on hover.

### CODE REVIEW

**Comment by dakshkhetan** [comment]
closes issue #277

**Comment by dakshkhetan** [comment]
Screenshots:

**Comment by dakshkhetan** [comment]
@hereisnaman Please review. 😀

**Comment by dakshkhetan** [comment]
Closes #277

**Comment by dakshkhetan** [comment]
@hereisnaman Please review. 😀

**Comment by dakshkhetan** [comment]
GIF for reference:

ScreenRecord

**Comment by dakshkhetan** [comment]
@hereisnaman Please review. 😀

**Comment by hereisnaman** [comment]
The issue has been closed.

**Pull request closed without merging**
