### PR TITLE
Added Full Screen Support

### PR DESCRIPTION
**Pull request by darshkpatel**
Added Fullscreen support for IDE 
Calls Native Full screen calls for major browsers using JS

### CODE REVIEW

**Comment by darshkpatel** [comment]
Any reviews?

**Comment by darshkpatel** [comment]
@omerjerk @abhishek97 ?

**Comment by abhishek97** [comment]
@darshkpatel  the fullscreen doesn't work for me. 
As you can see below, it shows up in a small box instead of resizing to occupy whole screen.
screen shot 2017-05-23 at 7 35 34 pm

**Comment by darshkpatel** [comment]
Let me look into it

**Pull request closed without merging**
