### PR TITLE
Download Code and Save Code in Browser Added

### PR DESCRIPTION
**Pull request by hereisnaman**
Download and Save code button added in editor.
Download button saves and download all the content of editor in a file with extension matching to the language being used. 

Save button saves all content in ~~cookies~~ localStorage.
Clear Button clear localStorage as well.
issue solved:https://github.com/coding-blocks/ide/issues/27

# Updated

## Download Button
image

## Save Button
image

# Previous
## With Download and Save Button
image

## File Downloaded with matching extension
image

## Downloaded File
image

### CODE REVIEW

**Comment by hereisnaman** [comment]
@championswimmer @prateek27 please check.

**Comment by abhishek97** [comment]
@hereisnaman  i think adding two separate buttons, one to Download the code and the second to save the code(which will persist refresh in browser) will be better. What do you think?

**Comment by hereisnaman** [comment]
@abhishek97 well this one was for downlaod code, I renamed the PR. Will look forward to add save feature too.

**Comment by hereisnaman** [comment]
@prateek27 screenshots updated.

**Comment by abhishek97** [comment]
You working on a non-cokiee solution?

**Comment by hereisnaman** [comment]
@abhishek97 yes I am working on that.

**Comment by hereisnaman** [comment]
@abhishek97 @prateek27 now saving code with localStorage rather than cookies. Thanks @abhishek97 for suggestion.

**Comment by prateek27** [comment]
Good and great @hereisnaman ! (y)
@abhishek97 Thanks for the suggestions. 
Added a bounty of 100 points.

**Pull request merged**
