### PR TITLE
Input Box Toggle Added

### PR DESCRIPTION
**Pull request by hereisnaman**
@championswimmer resolved: https://github.com/coding-blocks/ide/issues/50
image
### Close icon in input box panel heading closes the box and displays the custom input button back.
image

### CODE REVIEW

**Comment by astu9880** [comment]
@championswimmer  #51 Fixes the same issue.

**Comment by hereisnaman** [comment]
@championswimmer @prateek27 please review.

**Comment by hereisnaman** [comment]
@championswimmer this is having the feature of closing the box again.

**Comment by hereisnaman** [comment]
@championswimmer updated. Added close icon. 
screen shot 2017-05-28 at 2 26 03 am
screen shot 2017-05-28 at 2 26 08 am

**Comment by astu9880** [comment]
@hereisnaman Dude. Is this not copying?

**Comment by hereisnaman** [comment]
@astu9880 you took the idea of adding the icon, that is copying. I just fixed the margin.

**Comment by astu9880** [comment]
@hereisnaman yeah dude! Totally! The idea I incepted :) 
(We are all friends here. All of this goes to the same website. Please think before you make any allegations.)

**Comment by hereisnaman** [comment]
Think before you do this: 
image

And you can match the timestamp of who added the icon first and you didn't take the name of it before I added it to my PR.

**Comment by astu9880** [comment]
@hereisnaman This was to notify the admins that another parallel PR exists in case they don't notice. Mostly because github PRs appear reverse chronologically. I thought it through. Perhaps you should have too.
Anyway, let's just let @championswimmer decide. Enough with the hate :)

**Comment by hereisnaman** [comment]
@astu9880 oh there is no such hate bro :).

**Comment by championswimmer** [comment]
The tone of discussion going on between @hereisnaman and @astu9880 is just unhealthy. 
Please refrain from that. 

I will be going for #52 over #51 because as per the commit timestamps, @astu9880 did it before @hereisnaman

**Comment by omerjerk** [comment]
You don't seem to be handling the case of setting custom input to null when the custom input box is closed.

**Pull request closed without merging**
