### PR TITLE
Add Kotlin stub & update monaco-editor

### LINKED ISSUE #324: add stub and theme for lang: kotlin
We just introduced the support of a new language in our judge. Let's support it on our IDE as well.

- [ ] Add langMode [here](https://github.com/coding-blocks/ide/blob/master/src/components/editor/MonacoEditor.vue#L9) compatible with monaco editor
- [ ] Add a sample hello world code [here](https://github.com/coding-blocks/ide/blob/master/src/assets/js/sample-source.js) and export the language
    ```
     fun main(args: Array<String>) {
        println("Hello World")
     }
    ```

Test your submissions:
- [ ] Is the syntax highlighting working?
- [ ] Is the stub shown when language is changed?

### LINKED ISSUE #343: Syntax color highlighting not working for 'Kotlin' language
kotlin issue

### PR DESCRIPTION
**Pull request by dakshkhetan**
Fixes #324 
Fixes #343

This is happening because **Kotlin** support in `monaco-editor` was added from `v16.0`.
**Solution**: Upgrade to version (`v0.18.1`) of `monaco-editor`.

kotlin fix

### CODE REVIEW

**Comment by hereisnaman** [comment]
deployment seems to be failed. Deploy it on netlify for testing.

**Comment by dakshkhetan** [comment]
Okay.

**Comment by dakshkhetan** [comment]
@hereisnaman

I have deployed it on netlify with default language state as `kotlin` - https://ecstatic-beaver-223cd6.netlify.app

But here, it still shows deploy failed. 😕

**Comment by dakshkhetan** [comment]
@hereisnaman Please review. Thanks! :)

**Comment by dakshkhetan** [comment]
@hereisnaman bhaiya, please review this PR. 😀

**Comment by dakshkhetan** [comment]
@jatinkatyal13 Please review this too, thanks! :)

**Pull request merged**
