### PR TITLE
bug fixes and added modal before changing the language

### PR DESCRIPTION
**Pull request by mukulsaini**
Few Bugs :
1. After saving the code to local storage and then reloading the page, switching to different language was not working. 
 - Fixed!
2. Some font are not supported by the ace editor. Ace only supports monospace fonts for now, so cursor position is wrong for other fonts.  
 - Removed the unsupported fonts.

Added confirm box before switching to different language.

### CODE REVIEW

**Comment by hereisnaman** [comment]
@mukulsaini great to see you are too fast in finding bugs, thanks. There are many more bugs, which I have resolved in : https://github.com/coding-blocks/ide/pull/67 .

I really didn't know about supported fonts, so by mistake included those fonts too which are not supported.

Friend it is a request that you don't add the confirm popup for changing the lang, as it will be better to only let it replace the editor value in the first load only. Currently It don't update editor value if a file is uploaded.

As if a user wrote all the code and forgot to change the lang, then he will need to first copy the code and change the lang and then paste the code. 

Try on making it not replace the editor value once any changes in the editor are there. That will be better. :)

**Comment by mukulsaini** [comment]
@hereisnaman Keeping your point in mind that the editor value should not change on changing the language, I left it to the user to decide whether he wants to keep the editor value same or change to  default on changing the language. 
I added a popup which will be displayed when user switch to a different language only when he has made any changes to the editor.

image

If the user clicks "yes" it will  behave like you said that language will  change but not the value in the editor. If user does not wants to keep the value in editor he can select "no".

**Comment by mukulsaini** [comment]
@championswimmer @prateek27 please review the changes.

**Comment by hereisnaman** [comment]
@mukulsaini great work man, I asked a few people for review, it is nice but can't you just make it without modal. That, it automatically won't change the editor value once there are any changes. You can have a var for first load and change its value if any changes in the editor are there or the code is restored from the localStorage.  

Rather than the use of ifUpload you can use a var for this purpose. Currently the ifUpload is used to check if a file is uploaded and then don't let the dropdown update the editor value. 

You can eliminate the use of ifUpload and use some other variable to check for changes in editor and then don't let the dropdown update the editor. You'll also need to save that variable in localstorage, but a constant value for which the dropdown won't change the editor. So that if the code is loaded from local storage again the dropdown won't update the editor.

Sorry for lots of "dropdown won't change the editor" :P

**Comment by mukulsaini** [comment]
Doing things automatically can let user think like there is a bug in the application. On the first use, I also felt so I added a modal. Modal is necessary so that user can change to other language even when he did changes to the editor. 
I am using a var 'hasEditorChanged' to handle if the value of the editor has been changed. There is no need to store this variable in localstorage as we can set the value of 'hasEditorChanged' value to 'true' after loading code from the localstorage. 
The modal will be displayed only when the value of hasEditorChanged is true.

**Comment by hereisnaman** [comment]
Okay cool man. Lets keep it this way only then, great work. Just do one thing, change it to "keep the code in the editor" it will be more clear. 

Thanks, every single contribution making it better. 

👍🏻

**Comment by championswimmer** [comment]
added bounty directly to this PR. when submitting for claim use this PR's url for both issue and PR field

**Pull request merged**
