### PR TITLE
show current language & set language as upload ext

### PR DESCRIPTION
**Pull request by abhishek97**
Issue : #28

### CODE REVIEW

**Comment by hereisnaman** [comment]
You have not updated the lang variable. Resolved here: https://github.com/coding-blocks/ide/pull/30 .  Also lang value should be same as the already being used: 
image

@prateek27 please review: https://github.com/coding-blocks/ide/pull/30

**Comment by hereisnaman** [comment]
@abhishek97 showing lang is fine.

**Comment by abhishek97** [comment]
@hereisnaman Thanks, Fixed in the latest commit.

**Comment by omerjerk** [comment]
@abhishek97 What does this do exactly?

**Comment by abhishek97** [comment]
@omerjerk aimed to solve https://github.com/coding-blocks/ide/issues/28 , however i see https://github.com/coding-blocks/ide/pull/46 is merged against that. 

But #46  still doesn't set editor mode to the language selected. Currently the editor doesn't change language modes. We have another issue about it or merge this one.

**Comment by hereisnaman** [comment]
@abhishek97 what editor mode are you talking about ? Please explain, I didn't understand.

**Comment by abhishek97** [comment]
Try typing as lang=javascript

```
console.log('Hello World');
function fun1(){
 return 0;  
}

```

Notice the little to no syntax highlighting or structure.

**Comment by hereisnaman** [comment]
Okay, is there something wrong with what I did? I have updated the lang variable as per the uploaded file and have customized the language dropdown to not change editor content to lang_sample, one lang in changed, if a new file is uploaded. Once editor is cleared using the button, dropdown will start functioning as it did earlier. 

If you find any bug in that please notify me. :)

This what you are saying is other feature, or related to that only ?

**Pull request closed without merging**
