### PR TITLE
Fix #303 : add 'save' code button

### LINKED ISSUE #303: 'save' option not appearing in nav-bar
Screenshot 2020-05-17 at 11 55 46 PM

### PR DESCRIPTION
**Pull request by dakshkhetan**
Fixes #303 

Screenshot:
Screenshot 2020-05-18 at 12 08 00 AM

### CODE REVIEW

**Comment by hereisnaman** [comment]
Was just adding that. Thanks

**Comment by dakshkhetan** [comment]
@hereisnaman Also, dropdowns appear on `click` instead of `hover`.
Can I work on this?

**Comment by hereisnaman** [comment]
> @hereisnaman Also, dropdowns appear on `click` instead of `hover`.
> Can I work on this? Since it will be more intuitive for the users.

We do not need hover.

**Comment by ankiiitraj** [comment]
Hi, do you think save button should be in better reach like not in dropdown but in menubar

**Comment by hereisnaman** [comment]
> Hi, do you think save button should be in better reach like not in dropdown but in menubar

We can rather bind ctrl+S with the save action.

**Comment by hereisnaman** [comment]
Created an issue https://github.com/coding-blocks/ide/issues/305

**Pull request merged**
