### PR TITLE
added margin-top to notifications

### LINKED ISSUE #326: Add Margin to the Notification
Add top margin to the notification box to not overlap the navbar.

Screenshot 2020-05-20 at 5 29 47 AM

### PR DESCRIPTION
**Pull request by gurrrung**
Closes #326 
Added margin-top to all the notifications. ( I can do it only for success also but I think here it should be for errors too ).

Screenshot from 2020-05-20 08-43-39

### CODE REVIEW

**Comment by hereisnaman** [comment]
add 45px margin to `.notifications` class. Also I am unable to see the changes in the preview. Does it work?

**Comment by gurrrung** [comment]
Yeah, it looks like the screen attached. The error was overlapping earlier.

**Comment by gurrrung** [comment]
With my current CSS, 
Screenshot from 2020-05-20 09-11-25

**Comment by gurrrung** [comment]
45px looks like this.
Screenshot from 2020-05-20 09-13-22

**Comment by hereisnaman** [comment]
> 45px looks like this.
> Screenshot from 2020-05-20 09-13-22

The promo image is not loading up on local, on prod it will be displayed and take more height. In the closed state, it will be below the menu bar only.  Make it 45.

**Comment by gurrrung** [comment]
> The promo image is not loading up on local, on prod it will be displayed and take more height. In the closed state, it will be below the menu bar only. Make it 45.
I got it, saw the deployed version. Made the changes.

**Comment by gurrrung** [comment]
Ready for review.

**Pull request merged**
