### PR TITLE
[ Fixes: #282 ]View->Layout of input,output pane 

### LINKED ISSUE #282: View->Layout of input,output pane
The bottom input and output pane takes lot of space and is inconvenient when we code. We can have the input and output pane to the right side, this setup is quite convenient for coding and many programmers prefers this. 
Screenshot from 2020-05-16 09-10-06
 This layout view. One can get more space for the code part.

### PR DESCRIPTION
**Pull request by mnb27**
View->Layout of input,output pane added. Dock to bottom and dock to right view.
Fixes #282 @hereisnaman  GIF Attached!!
fi

https://deploy-preview-312--cb-ide.netlify.app/

### CODE REVIEW

**Comment by hereisnaman** [comment]
@mnb27 rebase with master and resolve conflicts

- change focus color for the buttons to red being used for the run button. 
- in the vertical layout, disable the resize for the input output boxes
- have a 6:4 split but restrict the width of io container to 550px.

make same changes in the other layout also, where the io container is not over the editor.

**Comment by mnb27** [comment]
> @mnb27 rebase with master and resolve conflicts
> 
> * change focus color for the buttons to red being used for the run button.
> * in the vertical layout, disable the resize for the input output boxes
> * have a 6:4 split but restrict the width of io container to 550px.
> 
> make same changes in the other layout also, where the io container is not over the editor.

@hereisnaman  You mean all icon buttons(copy,upload,toggle) to have red color or the dropdown option ?

**Comment by hereisnaman** [comment]
> > @mnb27 rebase with master and resolve conflicts
> > 
> > * change focus color for the buttons to red being used for the run button.
> > * in the vertical layout, disable the resize for the input output boxes
> > * have a 6:4 split but restrict the width of io container to 550px.
> > 
> > make same changes in the other layout also, where the io container is not over the editor.
> 
> @hereisnaman You mean all icon buttons(copy,upload,toggle) to have red color or the dropdown option ?

On hover and focus yes all of them

**Comment by mnb27** [comment]
@hereisnaman 
- Improved layout view
- Changed focus color for the icon buttons to red
- 6:4 split
- When input disabled, editor has full window size in both layouts

Preview here:
https://deploy-preview-312--cb-ide.netlify.app/

**Comment by mnb27** [comment]
@hereisnaman As you merged @dakshkhetan PR. My branch is having conflicts. So do I need to resolve the conflicts or not ? I mean my PR will be merged or not .

**Comment by hereisnaman** [comment]
> @hereisnaman As you merged @dakshkhetan PR. My branch is having conflicts. So do I need to resolve the conflicts or not ? I mean my PR will be merged or not .

I have merged the other PR. You can still claim 200 points for your efforts.

**Comment by mnb27** [comment]
> I have merged the other PR. You can still claim 200 points for your efforts.
@hereisnaman Ok..Can you please give more points :sweat_smile:
Thanks bhaiya for your support and continuous guidance.

**Comment by hereisnaman** [comment]
I think 200 are appropriate, in ideal case only 1 person with the first solution should be awarded. Closing this PR.

**Pull request closed without merging**
