### PR TITLE
Share styling updated

### PR DESCRIPTION
**Pull request by mnb27**
Fixes( part of ): #300 
Share modal styling is now consistent will other modals.
Screenshot:
share
@hereisnaman 
Review here: https://deploy-preview-368--cb-ide.netlify.app/

Suggest if any changes required.

### CODE REVIEW

**Comment by hereisnaman** [comment]
Color, borders everything is different. Please take a closer look to shortcuts and Download modal for reference.

**Comment by mnb27** [comment]
@hereisnaman 
Screenshot from 2020-05-25 11-06-49

Preview here: https://deploy-preview-368--cb-ide.netlify.app/

**Comment by hereisnaman** [comment]
@mnb27 I see a padding in the modal container which is not there in other modals. Also please make the esc key work.

**Comment by mnb27** [comment]
> @mnb27 I see a padding in the modal container which is not there in other modals. Also please make the esc key work.

-container padding removed
-Esc key is already working fine (GIF attached)
esc

Screenshot from 2020-05-25 12-04-17

**Comment by hereisnaman** [comment]
This looks good now. But the esc key is not working for me even in the latest preview. Can you please check.

**Comment by mnb27** [comment]
> This looks good now. But the esc key is not working for me even in the latest preview. Can you please check.

Here it the latest preview 368 (esc is working fine)
Screencast:-
Screencast-from-Monday-25-May-20

**Comment by hereisnaman** [comment]
> > This looks good now. But the esc key is not working for me even in the latest preview. Can you please check.
> 
> Here in the latest preview 368 (esc is working fine)
> Screencast:-
> Screencast-from-Monday-25-May-20

If I say after testing that it is not working for me, spend time on debugging if there is some issue. You can't keep on arguing that everything is fine.

Let me know if it is not working only on the preview or there is a  browser or OS specific issue.

I am on firefox right now.

**Comment by mnb27** [comment]
@hereisnaman 
Sorry!! for such reply.
But I have looked into it and it's working fine for me. I have tested on firefox,chrome .
OS :- Ubuntu

#289 PR
https://deploy-preview-289--cb-ide.netlify.app/ in this preview (esc working for you) ?

**Comment by hereisnaman** [comment]
> @hereisnaman
> Sorry!! for such reply.
> But I have looked into it and it's working fine for me. I have tested on firefox,chrome .
> OS :- Ubuntu
> 
> #289 PR
> https://deploy-preview-289--cb-ide.netlify.app/ in this preview (esc working for you) ?
> 
> Which OS are you testing on ? It seems to be OS specific issue.

I am on mac OS. Not working even in this preview, though the download modal is closing using esc.

**Comment by mnb27** [comment]
@hereisnaman 
Please check if esc is working fine or not ? (PS: Working fine om my laptop)
Latest preview: https://deploy-preview-368--cb-ide.netlify.app/

**Comment by hereisnaman** [comment]
> @hereisnaman
> Please check if esc is working fine or not ? (PS: Working fine om my laptop)
> Latest preview: https://deploy-preview-368--cb-ide.netlify.app/

@jatinkatyal13 is it working for you? Still now working for me.

**Comment by mnb27** [comment]
#285 issue 
#289 PR  
Why this issue got closed and PR merged ? if this was not working over mac OS

**Pull request closed without merging**
