### PR TITLE
fixes #313 - Added stub for lang: Go

### LINKED ISSUE #313: add stub for lang: go

### PR DESCRIPTION
**Pull request by ankiiitraj**
fixes #313 - Added stub for lang: Go

### CODE REVIEW

**Comment by ankiiitraj** [comment]
Hi @championswimmer Kindly review this PR. Thanks!

**Comment by ankiiitraj** [comment]
Followup : Should I change the stud or it is okay.

**Comment by championswimmer** [comment]
It should print Hello World too just like the other lang stubs

**Comment by ankiiitraj** [comment]
Done :)

**Pull request closed without merging**
