### PR TITLE
Keyboard shortcuts

### PR DESCRIPTION
**Pull request by sahilharjai**
Keyboard shortcuts Added.
** ctrl + Q : to run the program
** ctrl + B: to reset defaults.
** ctrl + M: to reset the code
 
Shortcuts button added in the menubar along with Modal

### CODE REVIEW

**Comment by abhishek97** [comment]
@sahilharjai 
`Ctrl+B` isn't working for me Safari/Chrome MacOs. Please test it.
Also please add some screenshots to the pr for the UI changes.

**Comment by sahilharjai** [comment]
Screenshots for UI changes
ui change1
ui change2

**Comment by hereisnaman** [comment]
ctrl+b working, can we also reset the the code to code_sample?

**Comment by abhishek97** [comment]
I think it'll be best to add another shortcut for resetting code. Resetting editor defaults should not change the code.

**Comment by sahilharjai** [comment]
Added ctrl+m to reset the code
codingide

**Comment by abhishek97** [comment]
Okay. This seems like an OS thing. `ctrl+b` still won't work for me, However `Ctrl + option + b` does. Please mention that in the shortcut popup. 

@hereisnaman  What browser version/OS are you using?

**Comment by hereisnaman** [comment]
@abhishek97 I am using chrome. Are you changing the editor settings?

**Comment by abhishek97** [comment]
@hereisnaman yes ofc. What version of chrome and operating system version?

**Comment by hereisnaman** [comment]
chrome 61 and high sierra

**Pull request merged**
