### PR TITLE
fixes #323 - Added save modal

### LINKED ISSUE #323: Add save file modal
Currently the filename input field is in the status bar at the bottom. On saving the file, the name is set to untitled if the value of the field is null.

On saving check if any file name exists, otherwise show a modal with the input field for the same and a save button in the modal footer. 

The value of the input field should be initialized by `code.<lang_ext>`. You need to maintain a map of extensions per language as being done for the download modal. Use a common lang-ext map for both the modals and add extensions for the missing langs.

Also in the download modal initialize the value of input field used in that modal for the name of file to be downloaded with the filename input in the status, but if the filename input is empty in the status, initialize in the similar way as already being done.

The modal should have dark bg.

### PR DESCRIPTION
**Pull request by ankiiitraj**
fixes #323 - Added save modal
Here is the working screenshot ---
simplescreenrecorder-2020-05-21_04 18 21(1)

### CODE REVIEW

**Comment by ankiiitraj** [comment]
Hi @hereisnaman kindly review the code and you can verify this here https://5ec5c38aef5c80000685a24a--cb-ide.netlify.app/
Let me know if changes are to be made

**Comment by hereisnaman** [comment]
- the status bar is not to be removed.
- modal colors doesn't match the theme. Have the modal background same as the editor bg and the modal header and footer border color as menubar bg. The buttons should be red in color nd match the run button style.

Save Modal:
- close button not required.

Download Modal:
- close, reset, save button not required.
- change filename when the value of input field is changed, no need to maintain separate state.
- Download Code -> DOWNLOAD


Both the modals are opened even when the filename is touched and exists. The confirm file name modal should not open after the user edits the filename for the first time or a filename already exists. Maintain a fileNameChange state and update it on first change it file which can be from the status bar or from the save and download modals. If the filename is not changed and the user saves/download the file with the default filename, save it as the filename and update the filename changed state.

Filename and filename changed state should be reset when new file is created or some other file is opened.

**Comment by ankiiitraj** [comment]
Hi @hereisnaman I am shifting title bar back to the place where it was as when banner appears and overflow-y is hidden , the title bar at bottom disappears

**Comment by ankiiitraj** [comment]
- [ ]     modal colors doesn't match the theme. Have the modal background same as the editor bg and the modal header and footer border color as menubar bg. The buttons should be red in color nd match the run button style.
 - [ ]    change filename when the value of input field is changed, no need to maintain separate state. 
 - [ ] Both the modals are opened even when the filename is touched and exists. The confirm file name modal should not open after the user edits the filename for the first time or a filename already exists. Maintain a fileNameChange state and update it on first change it file which can be from the status bar or from the save and download modals. If the filename is not changed and the user saves/download the file with the default filename, save it as the filename and update the filename changed state.
 - [ ] Filename and filename changed state should be reset when new file is created or some other file is opened. (As on new file opens in new tab every thing get reset own its own)

**Comment by ankiiitraj** [comment]
Kindly review this one @hereisnaman

**Comment by hereisnaman** [comment]
> Kindly review this one @hereisnaman

I am not sure if that is the correct deployment link you mentioned. Shows be the toolbar for settings there.

**Comment by hereisnaman** [comment]
> > > Kindly review this one @hereisnaman
> > 
> > 
> > I am not sure if that is the correct deployment link you mentioned. Shows be the toolbar for settings there.
> 
> If I got you right tool bar for setting is being solved here #310
> And this pull only solves save and download modal and I cross checked link is correct.
> Kindly have a look

Yeah my bad.

Earlier the modal shadow was not of blue color. Also few things are still remaining, like:

Download Code -> Download

And the status bar containing the file name input is not to be moved or changed, I don't know why you did all those changes, it is not mentioned in the issue.

Filename in the status bar also doesn't show the file extension.

**Comment by ankiiitraj** [comment]
> > > > Kindly review this one @hereisnaman
> > > 
> > > 
> > > I am not sure if that is the correct deployment link you mentioned. Shows be the toolbar for settings there.
> > 
> > 
> > If I got you right tool bar for setting is being solved here #310
> > And this pull only solves save and download modal and I cross checked link is correct.
> > Kindly have a look
> 
> Yeah my bad.
> 
> Earlier the modal shadow was not of blue color. Also few things are still remaining, like:
> 
> Download Code -> Download
> 
> And the status bar containing the file name input is not to be moved or changed, I don't know why you did all those changes, it is not mentioned in the issue.
> 
> Filename in the status bar also doesn't show the file extension.

Ok I'm fixing all these. BTW what does Download Code -> Download mean?

**Comment by ankiiitraj** [comment]
- [ ] Earlier the modal shadow was not of blue color. Also few things are still remaining, like:
- [ ] Download Code -> Download
- [ ] And the status bar containing the file name input is not to be moved or changed,
- [ ] Filename in the status bar also doesn't show the file extension.

Link for preview : https://deploy-preview-356--cb-ide.netlify.app/
Also first close the banner at the top, then only Title bar will be  visible as overflow in y is hidden
Done :) Kindly review @hereisnaman

**Pull request merged**
