### PR TITLE
Revert "Responsive UI Updates"

### PR DESCRIPTION
**Pull request by astu9880**
Reverts coding-blocks/ide#17
Not working for me. Still not responsive.
Here is the screenshot for iphone 6s (potrait)

### CODE REVIEW

**Comment by astu9880** [comment]
@hereisnaman @prateek27

**Comment by ashish1500616** [comment]
It seems that the commit has not been merged yet.It's too not responsive on my devices.

**Comment by hereisnaman** [comment]
I guess you have cache problem. Working fine on all my devices. Checked many 4-5 mobiles and 2 systems personally just know. Please clear your cache , re check and close this pr.

**Comment by ashish1500616** [comment]
I tried clearing my cache and reloading multiple times, but still the page look like this,
screen shot 2017-05-24 at 2 04 03 pm

**Comment by ashish1500616** [comment]
Here is a view after adding "viewport" to the code to the local repository.
screen shot 2017-05-24 at 2 07 54 pm

**Comment by hereisnaman** [comment]
Hey @ashish1500616 @astu9880 I prefered it doing without adding viewport because the columns widths needed to be increased and there were other things too which needed to be tweaked. In my PR, I increased the font sizes and other elements on the page. 

The page should not be displayed as just a scaled version of desktop version, but there were changes needed in the layout, which were must. 

I think it is looking fine without viewport. I even increased the height of editor for mobile devices because it is better than making user scroll inside the editor, now user can view more code together. 

Moreover people are working on adding full-screen button, which will also add a good functionality. 

Still @astu9880 if you think it is not working then you may submit a separate PR with updates, rather than just submitting a revert request. That would be a really better way and I will love to have it look more good.

**Comment by astu9880** [comment]
That is okay! For me having a scaled version is counter-intuitive to the original issue which was to add responsiveness. Closing revert request. Proposing PR with changes in a while :)

**Pull request closed without merging**
