### PR TITLE
updated theme

### LINKED ISSUE #1: improve the theme
right now it's just bootstrap 101. 
we need it better branded (using CB color scheme).

### PR DESCRIPTION
**Pull request by anu0012**
Fixed #1 
Added material design to it.

**Before**
screen shot 2017-05-16 at 4 38 01 pm

**After**
screen shot 2017-05-16 at 4 36 29 pm

### CODE REVIEW

**Comment by championswimmer** [comment]
UI changes need an accompanying screenshot (before/after).

**Comment by anu0012** [comment]
@championswimmer Updated with screenshots. Please take a look.

**Comment by championswimmer** [comment]
What we were looking for is an overall improvement in the theme and outlook of the website. Just changing bootstrap buttons to material buttons is of very little worth

**Comment by anu0012** [comment]
Hey @championswimmer take a look at this and give your feedback.

screen shot 2017-05-17 at 6 14 10 am

**Pull request closed without merging**
