### PR TITLE
Fixes #292: sharable-link not appearing in 'share' modal popup

### LINKED ISSUE #192: Share option doesn't display URL
The share option doesn't display the shareable link
Share

Console output: 
`
Access to XMLHttpRequest at 'https://cb.lk/api/v1/shorten' from origin 'https://ide.codingblocks.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

### LINKED ISSUE #280: Fix short url not loading issue
Screenshot from 2020-05-16 12-10-08

### LINKED ISSUE #292: sharable-link not appearing in "share" modal popup
Screenshot for reference:

issue

### PR DESCRIPTION
**Pull request by dakshkhetan**
Fixes #292 
Fixes #280 
Fixes #192 

- sharable-link now appears in share modal popup.
- notify user to save the code first (to generate new URL with saved code id) before sharing the code.

### CODE REVIEW

**Comment by dakshkhetan** [comment]
**Screenshots:**

When code is **not saved**, _error type notification_ appears:



When code is **saved**, link appears in 'share' modal popup:

**Comment by dakshkhetan** [comment]
@hereisnaman Please review. 😀

**Comment by dakshkhetan** [comment]
Also, if eligible, please add BOSS label and bounty.
Thanks!

**Comment by hereisnaman** [comment]
You just removed the short url feature here.

**Comment by dakshkhetan** [comment]
Yes, it was more of a temporary fix, just to keep the 'share' feature working.

**Comment by hereisnaman** [comment]
We are not looking for temporary fixes.

**Comment by dakshkhetan** [comment]
@hereisnaman Is CB URL Shortener still public?

**Pull request closed without merging**
