### PR TITLE
fixes #301 - added model for settings

### LINKED ISSUE #301: Add Modal for Editor Settings
Currently clicking on settings a tab appears. Create a new modal and move all the settings there. 

Screenshot 2020-05-17 at 11 45 24 PM

### PR DESCRIPTION
**Pull request by ankiiitraj**
Fixed #301 
Screenshot from 2020-05-18 11-41-59

### CODE REVIEW

**Comment by ankiiitraj** [comment]
Hi @hereisnaman , can you please review this and merge Thanks!

**Comment by hereisnaman** [comment]
Have a 2 column layout for modal body and text alignment left. For the footer, the two elements should be aligned to opposite ends.

**Comment by ankiiitraj** [comment]
Screenshot from 2020-05-18 19-25-17
Hi @hereisnaman kindly review. . .

P.S : I'm not that good with CSS

**Comment by hereisnaman** [comment]
> Screenshot from 2020-05-18 19-25-17
> Hi @hereisnaman kindly review. . .
> 
> P.S : I'm not that good with CSS

Best time to learn it then :) 

I'll wait for you to improve the styling.

**Comment by ankiiitraj** [comment]
Sure, One quick question what I actually have to do.
I currently used flexbox to not allow one row have more than 2 items. Is this not right?

**Comment by hereisnaman** [comment]
> Sure @hereisnaman , One quick question what I actually have to do.
> I currently used flexbox to not allow one row have more than 2 items. Is this not right?

Lets try with 1 column layout. The select fields are also to be aligned with the labels. Also match the button size with the share modal.

**Comment by hereisnaman** [comment]
@ankiiitraj what is the status on this? Also can you make it dark.

**Comment by ankiiitraj** [comment]
I will be make PR soon. I'm on it.
Sure I'll make it dark

**Comment by ankiiitraj** [comment]
Hi @hereisnaman . . . Does this seem right?
Screenshot from 2020-05-21 17-33-48

**Comment by hereisnaman** [comment]
> Hi @hereisnaman . . . Does this seem right?
> Screenshot from 2020-05-21 17-33-48

Good one. Last update you can do is to have the 2 col layout again but with labels above the input fields.

**Comment by hereisnaman** [comment]
> > Hi @hereisnaman . . . Does this seem right?
> > Screenshot from 2020-05-21 17-33-48
> 
> Good one. Last update you can do is to have the 2 col layout again but with labels above the input fields.

**Pull request closed without merging**
