### PR TITLE
Lang and Button HTML Updated as per upload file extension and lang

### PR DESCRIPTION
**Pull request by hereisnaman**
@prateek27 @championswimmer resolved: https://github.com/coding-blocks/ide/issues/28 

Did same in previous PR https://github.com/coding-blocks/ide/pull/30 but deleted fork by mistake and there were conflicts. It is orphan now and closing it. 

Please Merge this.

## Lang initialized
image

## Lang Update on FIle Upload
image

## Button HTML update on lang change
image

### CODE REVIEW

**Comment by championswimmer** [comment]
so if i upload a file which is Java. button becomes Java. Then I delete all text in the console. Then can I change language. Or I'll have to refresh page ?

**Comment by championswimmer** [comment]
Because the drop down is going away when we upload a file right ?

**Comment by hereisnaman** [comment]
Sir the lang variable which is used in pull and push data to the backend should be updated with uploading file. If i am writing code in c and then i upload a java file then that variable should be updated accordingly and also that variable is used to update the front end button html. 

If we have any other extension than the supported languages the lang variable will be set to c. 

Currently the variable dont get updated when we upload a file.

**Comment by hereisnaman** [comment]
# Live Test
## Uploaded a C++ file with the following content:
image

## Output: (as the lang variable is not updated)
image
@championswimmer @prateek27

**Comment by championswimmer** [comment]
What if I have a C++ file, with extension .c ? 
I am saying, you set the variable automatically, that's awesome. but also provide the option to manually change it after upload.

**Comment by hereisnaman** [comment]
@championswimmer it can anytime be changed using the dropdown.

**Comment by hereisnaman** [comment]
@championswimmer okay yeah, I'll have to add functionality that if file is uploaded then the dropdown won't make the editor content to get updated by the lang_sample. Please give me some time, I'll work on it.

**Comment by hereisnaman** [comment]
if cleared using the clear button then again the dropdown will update the editor with lang_sample when lang is changed by the user. @championswimmer will it be okay?

**Comment by hereisnaman** [comment]
@championswimmer I have resolved the issue completely. Now if you have uploaded the file, you can change the language from drop down and it won't update editor with language sample. Once you press clear button then again drop down will update the editor with language sample if language changed.

I uploaded a c++ file, lang changed to c++ automatically, then i changed language to java from dropdown, editor content remained the same. Please also see the console window in the ss below:
image

**Comment by championswimmer** [comment]
Looks good to me now !

**Pull request merged**
